ExpressionTest:expression_test.cpp
	g++ expression_test.cpp expression.cpp -o ExpressionTest -I /usr/local/lib/ -L /usr/lib/ -lgtest -lgtest_main -lpthread --std=c++11

.PHONY:clean
clean:
		rm -f ExpressionTest
